version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./logs:/app/logs
      - ./prices.db:/app/prices.db
    restart: unless-stopped
    command: python web_app.py

  scheduler:
    build: .
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - ./logs:/app/logs
      - ./prices.db:/app/prices.db
    restart: unless-stopped
    command: python scheduler.py
    depends_on:
      - web

  # Optional: Add a database service for production
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: sunkist
  #     POSTGRES_USER: sunkist
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: